app.name=Zyphora

# ================================
# Server Configuration
# ================================
server.port=8080

# ================================
# Database Configuration
# ================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.sslmode=require

# Hikari Connection Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=EcommerceHikariPool

# ================================
# JPA / Hibernate
# ================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.main.allow-bean-definition-overriding=true

# ================================
# JWT Configuration
# ================================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# ================================
# Brevo Email Configuration
# ================================
brevo.api.key=${BREVO_API_KEY}
user.mail=${USER_MAIL}

# ================================
# Logging
# ================================
logging.level.com.ecommerce=INFO
